name: Update cryptobib export and patch with dates
on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch: {}

jobs:
  build_cryptobib:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get install -y -qq myrepos
          sudo pip3 install pybtex unidecode
      - name: "Checkout cryptobib"
        run: |
          mr bootstrap https://raw.githubusercontent.com/cryptobib/cryptobib/master/mrconfig/mrconfig_https cryptobib
      - name: "Checkout our fork"
        uses: "actions/checkout@v4"
        with:
          path: "export"
          ref: "biblatex"
      - name: "Generate cryptobib"
        run: |
          cp export/resources/process.py export/resources/process2.py cryptobib/db
          cd cryptobib
          python3 db_tools/gen_abbrev.py
          cd db
          python3 process.py
          mv processed.bibyml abbrev.bibyml
          cd ..
          python3 db_tools/gen_abbrev.py
          cd db
          python3 process2.py > out.bib
          mv out.bib crypto_conf_list.bib
          cd ..
          python3 db_tools/gen.py
          cp db/abbrev*.bib db/changes.txt db/crypto.bib ../export
      - name: Check if we need to do a PR
        run: |
          export LINES_CHANGED=$(git diff --numstat --pretty="" | awk 'NF==3 {lines+=$1+$2} END {printf("%d", lines)}')
          echo "LINES_CHANGED=$LINES_CHANGED"
          echo "LINES_CHANGED=$LINES_CHANGED" >> $GITHUB_ENV
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        if: ${{ env.LINES_CHANGED > 10 }}
        with:
          commit-message: Update cryptobib
          title: Update cryptobib
          branch: update-cryptobib-biblatex
          path: export
          base: biblatex
          delete-branch: true
